# Generated by Django 2.2 on 2020-07-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200713_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
    ]
