# Generated by Django 2.2 on 2020-07-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_taskrecord_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='slug',
        ),
    ]
