# Generated by Django 2.2 on 2020-07-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_taskrecord_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.ManyToManyField(related_name='task', to='records.TaskRecord'),
        ),
    ]
