# Generated by Django 2.2 on 2020-07-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20200713_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskrecord',
            name='updated_at',
        ),
    ]
