# Generated by Django 2.2 on 2020-07-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20200716_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, related_name='task', to='records.TaskRecord'),
        ),
    ]
