# Generated by Django 2.2 on 2020-07-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20200716_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
