# Generated by Django 2.2 on 2020-07-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20200716_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='content',
            new_name='text',
        ),
    ]
